#pragma once

#include "energy/squared_error.h"
#include "energy/boundary_length.h"
#include "energy/total_area_potential.h"
#include "energy/total_volume_potential.h"
#include "energy/soft_area_constraint.h"
#include "energy/soft_volume_constraint.h"
#include "energy/implicit_attractor.h"
#include "energy/implicit_obstacle.h"
#include "energy/willmore_energy.h"

#include "energy/tpe_multipole_0.h"
#include "energy/tpe_multipole_nl_0.h"
#include "energy/tpe_multipole_pr_0.h"
#include "energy/tpe_barnes_hut_0.h"
#include "energy/tpe_barnes_hut_pr_0.h"
#include "energy/tpe_all_pairs.h"
#include "energy/tpe_all_pairs_pr.h"

#include "energy/tp_obstacle_multipole_0.h"
#include "energy/tp_obstacle_multipole_nl_0.h"
#include "energy/tp_obstacle_multipole_pr_0.h"
#include "energy/tp_obstacle_barnes_hut_0.h"
#include "energy/tp_obstacle_barnes_hut_pr_0.h"
#include "energy/tp_obstacle_all_pairs.h"
#include "energy/tp_obstacle_all_pairs_pr.h"
