#pragma once

#include "energy/all_pairs_tpe.h"
#include "energy/barnes_hut_tpe_6d.h"
#include "energy/squared_error.h"
#include "energy/boundary_length.h"
#include "energy/static_obstacle.h"
#include "energy/total_area_potential.h"
#include "energy/total_volume_potential.h"
#include "energy/barnes_hut_newtonian.h"
#include "energy/soft_area_constraint.h"
#include "energy/soft_volume_constraint.h"
#include "energy/implicit_attractor.h"
#include "energy/implicit_obstacle.h"
#include "energy/willmore_energy.h"
#include "energy/tpe_multipole_0.h"